routes/admin.php
<?php
use Illuminate\Support\Facades\Route;

Route::group(["prefix" => "admin", "middleware" => ["admin"], "namespace" => "Back"], function (){
    Route::get('/', ["as" => "admin", "uses" => "AdminController@index"]);

    //Route::resource('product', 'ProductController')->except('show');

    Route::group(["prefix" => "client"], function (){
       Route::group(["prefix" => "customers"], function (){
           Route::get('', ["as" => "client.customers.index", "uses" => "UserController@index"]);
           Route::get('{user_id}', ["as" => "client.customers.show", "uses" => "UserController@show"]);
       });
    });

    Route::group(["prefix" => "catalog"], function (){
        Route::group(["prefix" => "category"], function (){
            Route::get('', ["as" => "catalog.category.index", "uses" => "ProductCategoryController@index"]);
            Route::get('create', ["as" => "catalog.category.create", "uses" => "ProductCategoryController@create"]);
            Route::post('create', ["as" => "catalog.category.store", "uses" => "ProductCategoryController@store"]);
            Route::get('{category}', ["as" => "catalog.category.edit", "uses" => "ProductCategoryController@edit"]);
            Route::put('{category}', ["as" => "catalog.category.update", "uses" => "ProductCategoryController@update"]);
            Route::get('{category}/confirm', ["as" => "catalog.category.alert", "uses" => "ProductCategoryController@alert"]);
            Route::delete('{category}', ["as" => "catalog.category.destroy", "uses" => "ProductCategoryController@destroy"]);
        });

        Route::group(["prefix" => "product"], function (){
            Route::get('', ["as" => "catalog.product.index", "uses" => "ProductController@index"]);
            Route::get('create', ["as" => "catalog.product.create", "uses" => "ProductController@create"]);
            Route::post('create', ["as" => "catalog.product.store", "uses" => "ProductController@store"]);
            Route::get('{product}', ["as" => "catalog.product.edit", "uses" => "ProductController@edit"]);
            Route::put('{product}', ["as" => "catalog.product.update", "uses" => "ProductController@update"]);
            Route::get('{product}/confirm', ["as" => "catalog.product.alert", "uses" => "ProductController@alert"]);
            Route::delete('{product}', ["as" => "catalog.product.destroy", "uses" => "ProductController@destroy"]);
        });
    });

    Route::group(["prefix" => "orders"], function (){
        Route::get('', ["as" => "orders.index", "uses" => "OrderController@index"]);
        Route::get('{order_id}', ["as" => "orders.show", "uses" => "OrderController@show"]);
        Route::put('{order_id}', ["as" => "orders.update", "uses" => "OrderController@update"]);
        Route::post('{order_id}/invoice', ["as" => "orders.invoice", "uses" => "OrderController@invoice"]);
        Route::put('{order_id}/number', ["as" => "orders.updateNumber", "uses" => "OrderController@updateNumber"]);
    });

    Route::group(["prefix" => "configuration"], function (){
        Route::get('/', ["as" => "config.index", "uses" => "ConfigController@index"]);
        Route::get('boutique', ["as" => "config.boutique", "uses" => "ShopController@edit"]);
        Route::put('boutique', ["as" => "config.boutique.update", "uses" => "ShopController@update"]);

        Route::group(["prefix" => "pays"], function (){
            Route::get('/', ["as" => "config.pays.index", "uses" => "CountryController@index"]);
            Route::get('create', ["as" => "config.pays.create", "uses" => "CountryController@create"]);
            Route::post('create', ["as" => "config.pays.store", "uses" => "CountryController@store"]);
            Route::get('{pays}', ["as" => "config.pays.edit", "uses" => "CountryController@edit"]);
            Route::put('{pays}', ["as" => "config.pays.update", "uses" => "CountryController@update"]);
            Route::get('{pays}/confirm', ["as" => "config.pays.alert", "uses" => "CountryController@alert"]);
            Route::delete('{pays}', ["as" => "config.pays.destroy", "uses" => "CountryController@destroy"]);
        });

        Route::group(["prefix" => "etats"], function (){
            Route::get('/', ["as" => "config.etats.index", "uses" => "StateController@index"]);
            Route::get('create', ["as" => "config.etats.create", "uses" => "StateController@create"]);
            Route::post('create', ["as" => "config.etats.store", "uses" => "StateController@store"]);
            Route::get('{state_id}', ["as" => "config.etats.edit", "uses" => "StateController@edit"]);
            Route::put('{state_id}', ["as" => "config.etats.update", "uses" => "StateController@update"]);
            Route::get('{state_id}/confirm', ["as" => "config.etats.alert", "uses" => "StateController@alert"]);
            Route::delete('{state_id}', ["as" => "config.etats.destroy", "uses" => "StateController@destroy"]);
        });

        Route::group(["prefix" => "pages"], function (){
            Route::get('/', ["as" => "config.pages.index", "uses" => "PageController@index"]);
            Route::get('create', ["as" => "config.pages.create", "uses" => "PageController@create"]);
            Route::post('create', ["as" => "config.pages.store", "uses" => "PageController@store"]);
            Route::get('{state_id}', ["as" => "config.pages.edit", "uses" => "PageController@edit"]);
            Route::put('{state_id}', ["as" => "config.pages.update", "uses" => "PageController@update"]);
            Route::get('{state_id}/confirm', ["as" => "config.pages.alert", "uses" => "PageController@alert"]);
            Route::delete('{state_id}', ["as" => "config.pages.destroy", "uses" => "PageController@destroy"]);
        });

        Route::group(["prefix" => "maintenance"], function (){
            Route::get('/', ["as" => "config.maintenance.edit", "uses" => "MaintenanceController@edit"]);
            Route::put('/', ["as" => "config.maintenance.update", "uses" => "MaintenanceController@update"]);
            Route::put('cache', ["as" => "config.maintenance.cache", "uses" => "MaintenanceController@cache"]);
        });

    });
    Route::group(["prefix" => "expedition"], function (){
        Route::get('/', ["as" => "exp.index"]);

        Route::group(['prefix' => "range"], function (){
            Route::get('edit', ["as" => "exp.range.edit", "uses" => "RangeController@edit"]);
            Route::put('edit', ["as" => "exp.range.update", "uses" => "RangeController@update"]);
        });

        Route::group(["prefix" => "tarif"], function (){
            Route::get('edit', ["as" => "exp.colissimo.edit", "uses" => "ColissimoController@edit"]);
            Route::put('edit', ["as" => "exp.colissimo.update", "uses" => "ColissimoController@update"]);
        });
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
include('auth.php');

Route::get('/', ["as" => "home", "uses" => "HomeController@index"]);
Route::group(["prefix" => "boutique"], function (){
    Route::get('/', ["as" => "produits.index", "uses" => "ProductController@index"]);

    Route::group(["prefix" => "{category_id}"], function () {
        Route::get('/', ["as" => "produits.category", "uses" => "ProductController@category"]);
        Route::get('/produits/{produit_id}', ["as" => "produits.show", "uses" => "ProductController@show"]);
    });
});
Route::group(["prefix" => "panier"], function () {
    Route::get('/', ["as" => "panier.index", "uses" => "CartController@index"]);
    Route::post('/', ["as" => "panier.store", "uses" => "CartController@store"]);
    Route::get('/{id}', ["as" => "panier.destroy", "uses" => "CartController@destroy"]);
});
Route::group(["middleware" => ["auth"], "prefix" => "commandes"], function () {
    Route::get('create', ["as" => "commandes.create", "uses" => "OrderController@create"]);
    Route::post('/', ["as" => "commandes.store", "uses" => "OrderController@store"]);
    Route::get('confirmation/{order}', ["as" => "commandes.confirmation", "uses" => "OrdersController@confirmation"]);
    Route::post('payment/{order}', ["as" => "commandes.payment", "uses" => "PaymentController@payment"]);
});

Route::group(["middleware" => ["auth"], "prefix" => "account"], function () {
    Route::get('/', ["as" => "account", "uses" => "AccountController@index"]);
    Route::get('identite', ["as" => "account.identite.edit", "uses" => "IdentiteController@edit"]);
    Route::put('identite', ["as" => "account.identite.update", "uses" => "IdentiteController@update"]);
    Route::get('rgpd', ["as" => "account.rgpd", "uses" => "IdentiteController@rgpd"]);
    Route::get('rgpd/pdf', ["as" => "account.rgpd.pdf", "uses" => "IdentiteController@pdf"]);

    Route::group(["prefix" => "adresses"], function () {
        Route::get('/', ["as" => "account.adresses.index", "uses" => "AddressController@index"]);
        Route::get('create', ["as" => "account.adresses.create", "uses" => "AddressController@create"]);
        Route::post('create', ["as" => "account.adresses.store", "uses" => "AddressController@store"]);
        Route::get('{address}', ["as" => "account.adresses.edit", "uses" => "AddressController@edit"]);
        Route::put('{address}', ["as" => "account.adresses.update", "uses" => "AddressController@update"]);
        Route::get('{address}/delete', ["as" => "account.adresses.destroy", "uses" => "AddressController@destroy"]);
    });

    Route::group(["prefix" => "commande"], function () {
        Route::get('/', ["as" => "account.command.index", "uses" => "OrdersController@index"]);
        Route::get('{command_id}', ["as" => "account.command.show", "uses" => "OrdersController@show"]);
    });
});

include('admin.php');

//Auth::routes();
Route::get('page/{page:slug}', 'HomeController@page')->name('page');
Route::get('logout', 'Auth\LoginController@logout');
Route::get('test', 'TestController@test');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public $fillable = [
        'reference',
        'shipping',
        'total',
        'tax',
        'payment',
        'purchase_order',
        'pick',
        'invoice_id',
        'invoice_number',
        'state_id',
        'user_id'
    ];

    public function adresses()
    {
        return $this->hasMany(OrderAddress::class);
    }
    public function products()
    {
        return $this->hasMany(OrderProduct::class);
    }
    public function state()
    {
        return $this->belongsTo(State::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function payment_infos()
    {
        return $this->hasOne(Payment::class);
    }

    public function getPaymentTextAttribute($value)
    {
        $texts = [
            'carte' => 'Carte bancaire',
            'virement' => 'Virement',
            'cheque' => 'Chèque',
            'mandat' => 'Mandat administratif',
        ];
        return $texts[$this->payment];
    }
    public function getTotalOrderAttribute()
    {
        return $this->total + $this->shipping;
    }
    public function getTvaAttribute()
    {
        return $this->tax > 0 ? $this->total / (1 + $this->tax) * $this->tax : 0;
    }
    public function getHtAttribute()
    {
        return $this->total / (1 + $this->tax);
    }
}

resources/views/back/client/customers/show.blade.php
@extends("back.layouts.app")

@section("style")

@endsection

@section("subheader")
    @include("back.layouts.partials._subheader", [
    "active" => true,
    "titlePage" => "Information sur le client :".\App\Helpers\Generator::firsLetter($user->firstname).".".$user->name,
    "breads" => [
        [
            "name" => "Accueil",
            "url" => route('admin'),
            "last" => false
        ],
        [
            "name" => "Client",
            "url" => route('client.customers.index'),
            "last" => false
        ],
        [
            "name" => "Information sur le client :".\App\Helpers\Generator::firsLetter($user->firstname).".".$user->name,
            "url" => null,
            "last" => true
        ]
    ],
    "returnControl" => true,
    "btns" => []
])
@endsection

@section("content")
<div class="row">
    <div class="col-md-6">
        <div class="card card-custom gutter-b">
            <div class="card-header">
                <div class="card-title">
                    <span class="card-icon"><i class="la la-user-circle-o"></i> </span>
                    <h3 class="card-label">{{ $user->name }} {{ $user->firstname }} [{{ $user->id }}] - <a href="mailto:{{ $user->email }}">{{ $user->email }}</a></h3>
                </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td class="text-right">Date d'inscription</td>
                        <td class="text-left">{{ $user->created_at->format('d/m/Y à H:i') }} ({{ $user->created_at->diffForHumans() }})</td>
                    </tr>
                    <tr>
                        <td class="text-right">Dernière connexion</td>
                        <td class="text-left">{{ $user->last_seen->format('d/m/Y à H:i') }} ({{ $user->last_seen->diffForHumans() }})</td>
                    </tr>
                    <tr>
                        <td class="text-right">Inscription</td>
                        <td class="text-left">
                            @if($user->newsletter == 1)
                                <span class="label label-inline label-xl label-success"><i class="fa fa-check text-white"></i>&nbsp; Lettre d'information</span>
                            @else
                                <span class="label label-inline label-xl label-danger"><i class="fa fa-times text-white"></i>&nbsp; Lettre d'information</span>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <td class="text-right">Dernière mise à jour</td>
                        <td class="text-left">{{ $user->updated_at->format('d/m/Y à H:i') }} ({{ $user->updated_at->diffForHumans() }})</td>
                    </tr>
                    <tr>
                        <td class="text-right">Etat</td>
                        <td class="text-left">
                            @if($user->active == 1)
                                <span class="label label-inline label-xl label-success"><i class="fa fa-check text-white"></i>&nbsp; Actif</span>
                            @else
                                <span class="label label-inline label-xl label-danger"><i class="fa fa-times text-white"></i>&nbsp; Inactif</span>
                            @endif
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="card card-custom gutter-b">
            <div class="card-header">
                <div class="card-title">
                    <span class="card-icon"><i class="la la-shopping-basket"></i> </span>
                    <h3 class="card-label">Commandes <span class="label label-primary">{{ $user->orders->count() }}</span> </h3>
                </div>
            </div>
            <div class="card-body">
                <div class="card card-custom mb-10">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <strong>Commandes Validée:</strong> <span class="label label-success">{{ $countCommandeValid }}</span>
                                pour un montant de {{ \App\Helpers\Generator::formatCurrency($sumCommandValid) }}.
                            </div>
                            <div class="col-md-6">
                                <strong>Commandes Non Validée:</strong> <span class="label label-danger">{{ $countCommandeInvalid }}</span>
                                pour un montant de {{ \App\Helpers\Generator::formatCurrency($sumCommandInvalid) }}.
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Date</th>
                        <th>Paiement</th>
                        <th>Etat</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($user->orders as $order)
                        <tr>
                            <td>{{ $order->id }}</td>
                            <td>{{ $order->created_at->calendar() }}</td>
                            <td>{{ $order->payment_text }}</td>
                            <td><span class="label label-inline label-{{ $order->state->color }}">{{ $order->state->name }}</span> </td>
                            <td>{{ \App\Helpers\Generator::formatCurrency($order->total) }}</td>
                            <td>
                                <a href="{{ route('orders.show', $order->id) }}" class="btn btn-icon btn-sm btn-primary"><i class="fa fa-eye"></i> </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card card-custom gutter-b">
            <div class="card-header">
                <div class="card-title">
                    <span class="card-icon"><i class="la la-clock-o"></i> </span>
                    <h3 class="card-label">Dernières Connexions</h3>
                </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Date</th>
                        <th>Ip</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($user->connexions as $connexion)
                        <tr>
                            <td>{{ $connexion->id }}</td>
                            <td>{{ $connexion->created_at->format('d/m/Y à H:i') }}</td>
                            <td>{{ $connexion->ip }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
                <span class="card-icon"><i class="la la-map-pin"></i> </span>
                <h3 class="card-label">Liste des adresses</h3>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Société</th>
                            <th>Nom</th>
                            <th>Adresse</th>
                            <th>Pays</th>
                            <th>Téléphone</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($user->addresses as $address)
                        <tr>
                            <td>
                                @if($address->company) {{ $address->company }} @else (Néant) @endif
                            </td>
                            <td>{{ $address->civility }} {{ $address->name }} {{ $address->firstname }}</td>
                            <td>
                                {{ $address->address }}<br>
                                @if($address->addressbis) {{ $address->addressbis }} <br>@endif
                                @if($address->bp) {{ $address->bp }} <br>@endif
                                {{ $address->postal }} {{ $address->city }}
                            </td>
                            <td>{{ $address->country->name }}</td>
                            <td>{{ $address->phone }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section("script")
    <script type="text/javascript">
        // Initialization
        jQuery(document).ready(function () {

        });
    </script>
@endsection